# Generated by Django 5.1.7 on 2025-06-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
    ]
